import { Pencil, Plus, RefreshCw, Trash2, Package } from "lucide-react";
import { useEffect, useState } from "react";
import { EmptyState } from "../components/empty-state";
import { Loader } from "../components/loader";
import { PageHeader } from "../components/page-header";
import { PaginationControls } from "../components/pagination-controls";
import { Badge } from "../components/ui/badge";
import { Button } from "../components/ui/button";
import { Card, CardContent } from "../components/ui/card";
import { Dialog } from "../components/ui/dialog";
import { Input } from "../components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "../components/ui/select";
import { Spinner } from "../components/ui/spinner";
import { Table } from "../components/ui/table";
import * as api from "../lib/api";
import { useAuth } from "../lib/auth";
import { useToast } from "../lib/toast";
import { formatDate } from "../lib/utils";
import type { Competitor, CompetitorPayload, CompetitorProduct, CompetitorProductPayload } from "../types/admin";

type Mode = "add" | "edit" | null;
const emptyCompetitor: CompetitorPayload = { name: "", is_active: true };
const emptyProduct: CompetitorProductPayload = { name: "", is_type: "", en_type: "", competes_with: "", is_active: true };
const pageSize = 10;
const Status = ({ active }: { active: boolean }) => <Badge className={active ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-rose-200 bg-rose-50 text-rose-700"}>{active ? "active" : "inactive"}</Badge>;

export function CompetitorManagementPage() {
  const { token } = useAuth(); const { pushToast } = useToast();
  const [items,setItems]=useState<Competitor[]>([]), [total,setTotal]=useState(0), [page,setPage]=useState(1), [search,setSearch]=useState(""), [draftSearch,setDraftSearch]=useState(""), [statusFilter,setStatusFilter]=useState("all"), [loading,setLoading]=useState(true), [error,setError]=useState(""), [submitting,setSubmitting]=useState(false);
  const [mode,setMode]=useState<Mode>(null), [selected,setSelected]=useState<Competitor|null>(null), [form,setForm]=useState<CompetitorPayload>(emptyCompetitor);
  const [products,setProducts]=useState<CompetitorProduct[]>([]), [productsLoading,setProductsLoading]=useState(false), [productMode,setProductMode]=useState<Mode>(null), [selectedProduct,setSelectedProduct]=useState<CompetitorProduct|null>(null), [productForm,setProductForm]=useState<CompetitorProductPayload>(emptyProduct);
  async function load(){if(!token)return;setLoading(true);setError("");try{const r=await api.fetchCompetitors(token,{page,pageSize,search,statusFilter});setItems(r.items);setTotal(r.total)}catch(e){setError(e instanceof Error?e.message:"Unable to load competitors")}finally{setLoading(false)}}
  useEffect(()=>{void load()},[page,search,statusFilter,token]);
  async function showProducts(c:Competitor){if(!token)return;setSelected(c);setProductsLoading(true);try{setProducts((await api.fetchCompetitorProducts(token,c.id)).items)}catch(e){pushToast({tone:"error",title:"Unable to load products",description:e instanceof Error?e.message:"Unknown error"})}finally{setProductsLoading(false)}}
  const close=()=>{setMode(null);setSelected(null);setForm({...emptyCompetitor})}; const add=()=>{setForm({...emptyCompetitor});setSelected(null);setMode("add")}; const edit=(c:Competitor)=>{setSelected(c);setForm({id:c.id,name:c.name,is_active:c.is_active});setMode("edit")};
  const closeProduct=()=>{setProductMode(null);setSelectedProduct(null);setProductForm({...emptyProduct})}; const addProduct=()=>{setProductForm({...emptyProduct});setSelectedProduct(null);setProductMode("add")}; const editProduct=(p:CompetitorProduct)=>{setSelectedProduct(p);setProductForm({name:p.name,is_type:p.is_type,en_type:p.en_type,competes_with:p.competes_with,is_active:p.is_active});setProductMode("edit")};
  async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!token)return;setSubmitting(true);try{if(mode==="edit"&&selected)await api.updateCompetitor(token,selected.id,{name:form.name,is_active:form.is_active});else if(mode==="add")await api.createCompetitor(token,form);close();await load();pushToast({tone:"success",title:mode==="edit"?"Competitor updated":"Competitor created",description:form.name})}catch(x){pushToast({tone:"error",title:"Unable to save competitor",description:x instanceof Error?x.message:"Unknown error"})}finally{setSubmitting(false)}}
  async function saveProduct(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!token||!selected)return;setSubmitting(true);try{if(productMode==="edit"&&selectedProduct)await api.updateCompetitorProduct(token,selected.id,selectedProduct.id,productForm);else if(productMode==="add")await api.createCompetitorProduct(token,selected.id,productForm);closeProduct();await showProducts(selected);await load();pushToast({tone:"success",title:productMode==="edit"?"Product updated":"Product added",description:productForm.name})}catch(x){pushToast({tone:"error",title:"Unable to save product",description:x instanceof Error?x.message:"Unknown error"})}finally{setSubmitting(false)}}
  async function toggle(c:Competitor){if(!token)return;try{await api.setCompetitorActive(token,c.id,!c.is_active);await load()}catch(x){pushToast({tone:"error",title:"Status change failed",description:x instanceof Error?x.message:"Unknown error"})}}
  async function remove(c:Competitor){if(!token||!window.confirm(`Delete competitor ${c.name} and its products?`))return;try{await api.deleteCompetitor(token,c.id);if(selected?.id===c.id){setSelected(null);setProducts([])}await load()}catch(x){pushToast({tone:"error",title:"Delete failed",description:x instanceof Error?x.message:"Unknown error"})}}
  async function removeProduct(p:CompetitorProduct){if(!token||!selected||!window.confirm(`Delete product ${p.name}?`))return;try{await api.deleteCompetitorProduct(token,selected.id,p.id);await showProducts(selected);await load()}catch(x){pushToast({tone:"error",title:"Delete failed",description:x instanceof Error?x.message:"Unknown error"})}}
  if(loading&&!items.length)return <Loader label="Loading competitors..."/>;
  return <div className="space-y-6"><PageHeader title="Competitor Management" description="Manage competitor brands and products used in comparisons." actions={<><Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-2 size-4"/>Refresh</Button><Button onClick={add} className="text-white"><Plus className="mr-2 size-4"/>Add competitor</Button></>}/><Card><CardContent className="grid gap-4 p-5 md:grid-cols-[1fr_220px_160px]"><div><p className="mb-2 text-sm font-medium">Search competitors</p><Input value={draftSearch} onChange={e=>setDraftSearch(e.target.value)} placeholder="Search by name or ID"/></div><div><p className="mb-2 text-sm font-medium">Status</p><Select value={statusFilter} onValueChange={v=>setStatusFilter(v??"all")}><SelectTrigger><SelectValue placeholder="Status"/></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem><SelectItem value="active">Active</SelectItem><SelectItem value="inactive">Inactive</SelectItem></SelectContent></Select></div><Button className="self-end text-white" onClick={()=>{setPage(1);setSearch(draftSearch.trim())}}>Apply filters</Button></CardContent></Card>{error&&<p className="rounded-2xl bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</p>}{!items.length?<EmptyState title="No competitors found" description="Create a competitor brand to begin." action={<Button onClick={add}>Add competitor</Button>}/>:<Card className="overflow-hidden"><CardContent className="p-0"><Table><thead><tr><th className="px-5 py-4 text-left">Competitor</th><th className="px-5 py-4 text-left">Products</th><th className="px-5 py-4 text-left">Status</th><th className="px-5 py-4 text-left">Updated</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody>{items.map(c=><tr key={c.id} className="border-t"><td className="px-5 py-4"><p className="font-semibold">{c.name}</p><p className="text-xs text-muted-foreground">{c.id}</p></td><td className="px-5 py-4">{c.product_count}</td><td className="px-5 py-4"><Status active={c.is_active}/></td><td className="px-5 py-4 text-sm text-muted-foreground">{formatDate(c.updated_at)}</td><td className="px-5 py-4"><div className="flex justify-end gap-2"><Button size="sm" variant="outline" onClick={()=>void showProducts(c)}><Package className="mr-2 size-4"/>Products</Button><Button size="sm" variant="outline" onClick={()=>edit(c)}><Pencil className="mr-2 size-4"/>Edit</Button><Button size="sm" variant="ghost" onClick={()=>void toggle(c)}>{c.is_active?"Deactivate":"Activate"}</Button><Button size="sm" variant="destructive" onClick={()=>void remove(c)}><Trash2 className="mr-2 size-4"/>Delete</Button></div></td></tr>)}</tbody></Table><PaginationControls page={page} pageSize={pageSize} total={total} onPageChange={setPage}/></CardContent></Card>}
  <Dialog open={!!selected} title={selected?`${selected.name} products`:"Products"} description="Manage competitor products using the backend contract." onClose={()=>{setSelected(null);setProducts([]);closeProduct()}} footer={<div className="flex justify-end"><Button onClick={addProduct}><Plus className="mr-2 size-4"/>Add product</Button></div>}>{productsLoading?<div className="flex justify-center py-8"><Spinner/></div>:!products.length?<EmptyState title="No products" description="Add the first product." action={<Button onClick={addProduct}>Add product</Button>}/>:<div className="space-y-3">{products.map(p=><div key={p.id} className="flex flex-col gap-3 rounded-2xl border p-4 md:flex-row md:items-center md:justify-between"><div><p className="font-semibold">{p.name}</p><p className="text-sm text-muted-foreground">{p.is_type||"No IS type"} · {p.en_type||"No EN type"} · {p.competes_with||"—"}</p><Status active={p.is_active}/></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>editProduct(p)}><Pencil className="mr-2 size-4"/>Edit</Button><Button size="sm" variant="destructive" onClick={()=>void removeProduct(p)}><Trash2 className="mr-2 size-4"/>Delete</Button></div></div>)}</div>}</Dialog>
  <Dialog open={!!mode} title={mode==="edit"?"Edit competitor":"Add competitor"} description="Name is required; ID is generated when omitted." onClose={close} footer={<div className="flex justify-end gap-3"><Button variant="ghost" onClick={close}>Cancel</Button><Button type="submit" form="competitor-form" disabled={submitting}>{submitting?<Spinner className="mr-2 size-4"/>:null}{mode==="edit"?"Save changes":"Create competitor"}</Button></div>}><form id="competitor-form" onSubmit={save} className="space-y-4"><label className="block space-y-2 text-sm font-medium">Name<Input required value={form.name} onChange={e=>setForm(x=>({...x,name:e.target.value}))}/></label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={form.is_active} onChange={e=>setForm(x=>({...x,is_active:e.target.checked}))}/>Active</label></form></Dialog>
  <Dialog open={!!productMode} title={productMode==="edit"?"Edit competitor product":"Add competitor product"} description="Product name is required; IS type, EN type, and competes_with are optional." onClose={closeProduct} footer={<div className="flex justify-end gap-3"><Button variant="ghost" onClick={closeProduct}>Cancel</Button><Button type="submit" form="product-form" disabled={submitting}>{submitting?<Spinner className="mr-2 size-4"/>:null}Save product</Button></div>}><form id="product-form" onSubmit={saveProduct} className="grid gap-4 md:grid-cols-2"><label className="space-y-2 text-sm font-medium md:col-span-2">Product name<Input required value={productForm.name} onChange={e=>setProductForm(x=>({...x,name:e.target.value}))}/></label><label className="space-y-2 text-sm font-medium">IS type<Input value={productForm.is_type} onChange={e=>setProductForm(x=>({...x,is_type:e.target.value}))}/></label><label className="space-y-2 text-sm font-medium">EN type<Input value={productForm.en_type} onChange={e=>setProductForm(x=>({...x,en_type:e.target.value}))}/></label><label className="space-y-2 text-sm font-medium md:col-span-2">Competes with<Input value={productForm.competes_with} onChange={e=>setProductForm(x=>({...x,competes_with:e.target.value}))}/></label><label className="flex items-center gap-3 text-sm md:col-span-2"><input type="checkbox" checked={productForm.is_active} onChange={e=>setProductForm(x=>({...x,is_active:e.target.checked}))}/>Active</label></form></Dialog></div>;
}